# Generated by Django 5.2.8 on 2025-11-25 01:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('ID_Region', models.AutoField(primary_key=True, serialize=False)),
                ('Coordinates', models.CharField(max_length=50, unique=True, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('ID_Role', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Role', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('ID_Object', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Object', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('Length', models.FloatField(verbose_name='Длина')),
                ('Width', models.FloatField(verbose_name='Ширина')),
                ('Type_Of_Fence', models.CharField(choices=[('wood', 'Деревянный'), ('metal', 'Металлический'), ('concrete', 'Бетонный'), ('chainlink', 'Сетка-рабица'), ('other', 'Другой')], max_length=50, verbose_name='Тип ограждения')),
                ('ID_Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'unique_together': {('ID_Region', 'Name_Object')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ID_User', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('Patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('Login', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Логин')),
                ('Password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('ID_Role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.roles', verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Session_History',
            fields=[
                ('ID_Session', models.AutoField(primary_key=True, serialize=False)),
                ('Main_Guard_Surname', models.CharField(max_length=50, verbose_name='Фамилия главного охранника')),
                ('Date', models.DateField(verbose_name='Дата сессии')),
                ('Time', models.TimeField(verbose_name='Время сессии')),
                ('ID_Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objects', verbose_name='Объект')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История сессии',
                'verbose_name_plural': 'История сессий',
                'ordering': ['-Date', '-Time'],
                'unique_together': {('ID_User', 'ID_Object', 'Date', 'Time')},
            },
        ),
    ]
