# Generated by Django 4.2.9 on 2025-11-26 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('ID_Object', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Object', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('Perimeter', models.FloatField(verbose_name='Периметр')),
                ('Type_Of_Fence', models.CharField(choices=[('wood', 'Деревянный'), ('metal', 'Металлический'), ('concrete', 'Бетонный'), ('chainlink', 'Сетка-рабица'), ('brick', 'Кирпичный'), ('other', 'Другой')], max_length=50, verbose_name='Тип ограждения')),
                ('Coordinates', models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('ID_Region', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Region', models.CharField(max_length=50, unique=True, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Session_History',
            fields=[
                ('ID_Session', models.AutoField(primary_key=True, serialize=False)),
                ('Main_Guard_Surname', models.CharField(max_length=50, verbose_name='Фамилия главного охранника')),
                ('Date', models.DateField(verbose_name='Дата сессии')),
                ('Time', models.TimeField(verbose_name='Время сессии')),
                ('ID_Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objects', verbose_name='Объект')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_histories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История сессии',
                'verbose_name_plural': 'История сессий',
                'ordering': ['-Date', '-Time'],
            },
        ),
        migrations.AddField(
            model_name='objects',
            name='ID_Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.regions', verbose_name='Регион'),
        ),
    ]
